encoding: UTF-8

collections:
  projects:
    output: true
    permalink: /projects/:path/
    id: ""
    title: ""
    url: ""
    problem: ""
    solution: ""
    shortdesc: ""
    image: ""
    tags: []
    files: []
    permalink: /projects/:path/

url: "//automateyourlife.org/"
asset_path: "/assets/"
image_path: "/assets/images/"
script_path: "/assets/scripts/"
style_path: "/assets/styles/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: projects
    values:
      layout: "project"
