collections:
  projects:
    output: false
    id: ""
    title: ""
    url: ""
    problem: ""
    solution: ""
    image: ""
    tags: []

asset_path: "assets/"
image_path: "assets/images/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
