collections:
  projects:
    output: true
    id: ""
    title: ""
    url: ""
    problem: ""
    solution: ""
    image: ""
    tags: []
    permalink: /projects/:path/

asset_path: "assets/"
image_path: "assets/images/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: projects
    values:
      layout: "default"
