encoding: UTF-8

collections:
    projects:
        output: true
        permalink: /projects/:path/

url: "//automateyourlife.org/"
asset_path: "/assets/"
image_path: "/assets/images/"
script_path: "/assets/scripts/"
style_path: "/assets/styles/"

defaults:
  - scope:
        path: ""
    values:
        layout: "default"
  - scope:
        path: ""
        type: posts
    values:
        # Common values for both blog posts and projects
        title: ""
        image: ""
        tags: []

        # Settings applicable to blog posts only
        layout: "post"
        permalink: "/blog/:year/:month/:day/:title/"
        category: "blog"

        # Settings applicable to project posts only
        problem: ""
        solution: ""
        overview: ""
        requirements: []
        files: []
